//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alineacion
    {
        public int alineacion_id { get; set; }
        public Nullable<int> partido_id { get; set; }
        public Nullable<int> jugador_id { get; set; }
        public Nullable<int> jug_score_id { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual JugadorScore JugadorScore { get; set; }
        public virtual Partido Partido { get; set; }
    }
}
