//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direccion()
        {
            this.Torneo = new HashSet<Torneo>();
        }
    
        public int direccion_id { get; set; }

        [Display(Name = "Calle")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100)]
        public string direccion_calle { get; set; }

        [Display(Name = "Referencia")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(200)]
        public string direccion_referencia { get; set; }
        public Nullable<int> ciuadad_id { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneo> Torneo { get; set; }
    }
}
