//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Jugador = new HashSet<Jugador>();
            this.TorneoEquipo = new HashSet<TorneoEquipo>();
        }
    
        public int equipo_id { get; set; }
        public string equipo_nombre { get; set; }
        public string equipo_representante { get; set; }
        public string equipo_celular { get; set; }
        public string equipo_telefono { get; set; }
        public string equipo_estado { get; set; }
        public Nullable<int> imagen_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugador> Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TorneoEquipo> TorneoEquipo { get; set; }
        public virtual Imagen Imagen { get; set; }
    }
}
