//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Jugador = new HashSet<Jugador>();
            this.TorneoEquipo = new HashSet<TorneoEquipo>();
        }
    
        public int equipo_id { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100)]
        [DataType(DataType.Text)]
        public string equipo_nombre { get; set; }

        [Display(Name = "Representante")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100)]
        [DataType(DataType.Text)]
        public string equipo_representante { get; set; }

        [Display(Name = "Celular")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100)]
        [DataType(DataType.PhoneNumber)]
        public string equipo_celular { get; set; }

        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100)]
        [DataType(DataType.PhoneNumber)]
        public string equipo_telefono { get; set; }

        [Display(Name = "Estado")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100)]
        public string equipo_estado { get; set; }
        public Nullable<int> imagen_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugador> Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TorneoEquipo> TorneoEquipo { get; set; }
        public virtual Imagen Imagen { get; set; }
    }
}
