//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public int estadistica_id { get; set; }
        public Nullable<int> estadistica_puntos { get; set; }
        public Nullable<int> estadistica_victorias { get; set; }
        public Nullable<int> estadistica_derrotas { get; set; }
        public Nullable<int> estadistica_empates { get; set; }
        public Nullable<int> estadistica_gol_favor { get; set; }
        public Nullable<int> estadistica_gol_contra { get; set; }
        public Nullable<int> estadistica_gol_diferencia { get; set; }
        public Nullable<int> fase_equ_id { get; set; }
    
        public virtual FaseEquipo FaseEquipo { get; set; }
    }
}
