//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaseGrupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FaseGrupo()
        {
            this.Grupo = new HashSet<Grupo>();
        }
    
        public int faseg_id { get; set; }
        public string faseg_nombre { get; set; }
        public System.DateTime faseg_fecha { get; set; }
        public int faseg_numero_grupos { get; set; }
        public int faseg_al_mejor_de { get; set; }
        public string faseg_estado { get; set; }
        public Nullable<int> torneo_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
