//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            this.Alineacion = new HashSet<Alineacion>();
            this.Sancion = new HashSet<Sancion>();
        }
    
        public int jugador_id { get; set; }

        [Display(Name = "Cédula")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(10)]
        [DataType(DataType.Text)]
        public string jugador_cedula { get; set; }

        [Display(Name = "Nombres")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public string jugador_nombres { get; set; }

        [Display(Name = "Apellidos")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public string jugador_apellidos { get; set; }

        [Display(Name = "Número Camiseta")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int jugador_dorsal { get; set; }

        [Display(Name = "Edad")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int jugador_edad { get; set; }

        [Display(Name = "Estado")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50)]
        public string jugador_estado { get; set; }
        public Nullable<int> imagen_id { get; set; }
        public Nullable<int> equipo_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alineacion> Alineacion { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Imagen Imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sancion> Sancion { get; set; }
    }
}
