//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FutbolEntities : DbContext
    {
        public FutbolEntities()
            : base("name=FutbolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alineacion> Alineacion { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Estadistica> Estadistica { get; set; }
        public virtual DbSet<FaseEliminatoria> FaseEliminatoria { get; set; }
        public virtual DbSet<FaseEquipo> FaseEquipo { get; set; }
        public virtual DbSet<FaseGrupo> FaseGrupo { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Imagen> Imagen { get; set; }
        public virtual DbSet<Jornada> Jornada { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<JugadorScore> JugadorScore { get; set; }
        public virtual DbSet<Noticia> Noticia { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Partido> Partido { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Resultado> Resultado { get; set; }
        public virtual DbSet<Sancion> Sancion { get; set; }
        public virtual DbSet<Torneo> Torneo { get; set; }
        public virtual DbSet<TorneoEquipo> TorneoEquipo { get; set; }
    }
}
