//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int noticia_id { get; set; }
        public string noticia_titulo { get; set; }
        public string noticia_descripcion { get; set; }
        public Nullable<int> imagen_id { get; set; }
        public Nullable<int> torneo_id { get; set; }
    
        public virtual Imagen Imagen { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
