//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int pago_id { get; set; }

        [Display(Name = "Fecha Pago")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.Date)]
        public System.DateTime pago_fecha { get; set; }

        [Display(Name = "Valor Pago")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.Currency)]
        public decimal pago_valor { get; set; }

        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.MultilineText)]
        public string pago_descripcion { get; set; }
        public Nullable<int> tor_equ_id { get; set; }
    
        public virtual TorneoEquipo TorneoEquipo { get; set; }
    }
}
