//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado
    {
        public int resultado_id { get; set; }
        public Nullable<int> resultado_id_equipo_ganador { get; set; }
        public Nullable<int> resultado_goles_ganador { get; set; }
        public Nullable<int> resultado_goles_perdedor { get; set; }
        public Nullable<bool> resultado_empate { get; set; }
        public Nullable<int> partido_id { get; set; }
    
        public virtual Partido Partido { get; set; }
    }
}
