//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sancion
    {
        public int sancion_id { get; set; }
        public string sancion_titulo { get; set; }
        public string sancion_descripcion { get; set; }
        public string sancion_estado { get; set; }
        public Nullable<decimal> sancion_valor_multa { get; set; }
        public Nullable<int> partido_id { get; set; }
        public Nullable<int> jugador_id { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Partido Partido { get; set; }
    }
}
