//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Torneo()
        {
            this.Noticia = new HashSet<Noticia>();
            this.TorneoEquipo = new HashSet<TorneoEquipo>();
        }
    
        public int torneo_id { get; set; }
        public string torneo_nombre { get; set; }
        public System.DateTime torneo_fecha_inicio { get; set; }
        public System.TimeSpan torneo_hora_inicio { get; set; }
        public string torneo_estado { get; set; }
        public decimal torneo_precio { get; set; }
        public string torneo_descripcion { get; set; }
        public Nullable<int> direccion_id { get; set; }
        public Nullable<int> imagen_id { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Imagen Imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Noticia> Noticia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TorneoEquipo> TorneoEquipo { get; set; }
    }
}
